### ISSUE TITLE
Crash in fall handler

### ISSUE THREAD

**Issue by Sinhika** [Sinhika/simplecobalt#1]
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 11/13/14 8:48 AM
Description: Ticking player

java.lang.NullPointerException: Ticking player
    at akkamaddi.simplecobalt.code.HandlerArmor.onFallDamage(HandlerArmor.java:24)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_258_HandlerArmor_onFallDamage_LivingAttackEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at net.minecraftforge.common.ForgeHooks.onLivingAttack(ForgeHooks.java:285)
    at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:978)
    at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:491)
    at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:198)
    at net.minecraft.entity.Entity.func_70071_h_(Entity.java:318)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1559)
    at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288)
    at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:295)
    at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303)
    at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137)
    at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.func_148833_a(SourceFile:20)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at akkamaddi.simplecobalt.code.HandlerArmor.onFallDamage(HandlerArmor.java:24)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_258_HandlerArmor_onFallDamage_LivingAttackEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at net.minecraftforge.common.ForgeHooks.onLivingAttack(ForgeHooks.java:285)
    at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:978)
    at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:491)
    at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:198)
    at net.minecraft.entity.Entity.func_70071_h_(Entity.java:318)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1559)
    at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288)

-- Player being ticked --
Details:
    Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
    Entity ID: 248
    Entity Name: Sinhika
    Entity's Exact location: 469.54, 8.40, -146.16
    Entity's Block location: World: (469,8,-147), Chunk: (at 5,0,13 in 29,-10; contains blocks 464,0,-160 to 479,255,-145), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
    Entity's Momentum: 0.00, 0.00, 0.00
Stacktrace:
    at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:295)
    at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303)
    at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137)
    at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.func_148833_a(SourceFile:20)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
    Connection: net.minecraft.network.NetworkManager@586593da
Stacktrace:
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_60, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 993846696 bytes (947 MB) / 1332215808 bytes (1270 MB) up to 1852833792 bytes (1767 MB)
    JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1988M -Xms1G -XX:MaxPermSize=126M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 1, tallocated: 14
    FML: MCP v9.05 FML v7.10.85.1231 Minecraft Forge 10.13.2.1231 88 mods loaded, 88 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{7.10.85.1231} [Forge Mod Loader](forge-1.7.10-10.13.2.1231.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{10.13.2.1231} [Minecraft Forge](forge-1.7.10-10.13.2.1231.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CodeChickenCore{1.0.3.26} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    <CoFH ASM>{000} [CoFH ASM Data Initialization](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NotEnoughItems{1.0.3.57} [Not Enough Items](NotEnoughItems-1.7.10-1.0.3.57-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenModsCore{0.6} [OpenModsCore](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    simpleores{1.4.3} [SimpleOres 2]([1.7.10] SimpleOres 2   Plugins v1.4.3 .jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    aestheticsplugin{1.0.0} [SimpleOres 2 Aesthetics Plugin]([1.7.10] SimpleOres 2   Plugins v1.4.3 .jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    fusionplugin{1.4.3} [SimpleOres 2 Fusion Plugin]([1.7.10] SimpleOres 2   Plugins v1.4.3 .jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    netherrocks{1.1.2} [SimpleOres 2 Netherrocks Plugin]([1.7.10] SimpleOres 2   Plugins v1.4.3 .jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    morefusionfurnaces{1.0} [More Fusion Furnaces]([1.7.2]MoreFusionFurnaces.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    netherrocksAddenda{1.0.1} [akkamaddi's Addenda to Netherrocks]([1.7.2]Netherrocks Addenda.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    onlysilver{1.9.4-1.7.2} [OnlySilver](OnlySilver-1.9.4-1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    SilverRecycle{1.2.0} [Recycle Your Silver Recipes]([1.7.2]Recycle Your Silver.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    akkamaddiAddenda{1.0.1} [akkamaddi's Addenda]([1.7.2]Simple Ores Addenda.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MoCreatures{6.3.0} [DrZhark's Mo'Creatures Mod](DrZharks MoCreatures Mod v6.3.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    akkamaddicore{1.7.10-1.0.3} [akkamaddi's Core API](akkamaddiCore-1.7.10-1.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AppleCore{1.0.0} [AppleCore](AppleCore-mc1.7.10-1.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships](ArchimedesShips-1.7.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    arsenic{1.7.10-1.4.2} [Simple Arsenic and Old Lace](ArsenicAndLace-1.7.10-1.4.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ashenwheat{1.7.10-1.2.0} [Ashenwheat](ashenwheat-1.7.10-1.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Backpack{2.0.0} [Backpack](backpack-2.0.0-1.7.x.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiblioCraft{1.9.0} [BiblioCraft](BiblioCraft[v1.9.0][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Mantle{1.7.10-0.3.1.jenkins180} [Mantle](Mantle-mc1.7.10-0.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Natura{2.2.0} [Natura](natura-1.7.10-2.2.0-b1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiomesOPlenty{2.1.0} [Biomes O' Plenty](BiomesOPlenty-1.7.10-2.1.0.1004-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiblioWoodsBoP{1.9} [BiblioWoods Biomes O'Plenty Edition](BiblioWoods[BiomesOPlenty][v1.9].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ExtrabiomesXL{3.16.0} [ExtrabiomesXL](extrabiomesxl_1.7.10-3.16.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiblioWoodsEBXL{1.4} [BiblioWoods ExtraBiomesXL Edition](BiblioWoods[ExtraBiomesXL][v1.4].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiblioWoodsNatura{1.5} [BiblioWoods Natura Edition](BiblioWoods[Natura][v1.5].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Baubles{1.0.1.8} [Baubles](Baubles-1.7.10-1.0.1.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Thaumcraft{4.2.0.1} [Thaumcraft](Thaumcraft-1.7.10-4.2.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Botania{r1.3-135} [Botania](Botania r1.3-135.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CarpentersBlocks{3.3.0.1} [Carpenter's Blocks](Carpenter's Blocks v3.3.0.1 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    chisel{1.5.7} [Chisel](Chisel-1.7.10-1.5.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    classicalalchemy{1.7.10-1.2.2} [Classical Alchemy](ClassicalAlchemy-1.7.10-1.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHCore{1.7.10R3.0.0B8} [CoFH Core](CoFHCore-[1.7.10]3.0.0B8-36.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Waila{1.5.4a} [Waila](Waila-1.5.4a_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TConstruct{1.7.10-1.7.0.build665} [Tinkers' Construct](TConstruct-1.7.10-1.7.0d2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ExtraTiC{0.8.4} [ExtraTiC](ExtraTiC-1.7.10-1.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ExtraUtilities{1.1.0k} [Extra Utilities](extrautilities-1.1.0k.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FastCraft{1.9} [FastCraft](fastcraft-1.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FlatSigns{2.0.0.17} [Flat Signs](FlatSigns-1.7.10-universal-2.0.0.17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    GardenCore{1.2.0} [Garden Core](GardenStuff-1.7.10-1.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    GardenContainers{1.2.1} [Garden Containers](GardenStuff-1.7.10-1.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    GardenTrees{1.2.0} [Garden Trees](GardenStuff-1.7.10-1.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Growthcraft{2.1.0a} [Growthcraft](growthcraft-core-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Growthcraft|Cellar{2.1.0a} [Growthcraft Cellar](growthcraft-cellar-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Growthcraft|Apples{2.1.0} [Growthcraft Apples](growthcraft-apples-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Growthcraft|Bamboo{2.1.0} [Growthcraft Bamboo](growthcraft-bamboo-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Growthcraft|Bees{2.1.0} [Growthcraft Bees](growthcraft-bees-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Growthcraft|Fishtrap{2.1.0a} [Growthcraft Fishtrap](growthcraft-fishtrap-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Growthcraft|Grapes{2.1.0} [Growthcraft Grapes](growthcraft-grapes-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Growthcraft|Hops{2.1.0} [Growthcraft Hops](growthcraft-hops-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Growthcraft|Rice{2.1.0a} [Growthcraft Rice](growthcraft-rice-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    haditecoal{1.2.0} [Hadite Coal](hadite-1.7.10-1.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IronChest{6.0.62.742} [Iron Chest](ironchest-1.7.10-6.0.62.742-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    JABBA{1.1.4} [JABBA](Jabba-1.1.4_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    journeymap{4.0.5} [JourneyMap](JourneyMap4.0.5_Unlimited_MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    LunatriusCore{1.1.2.14} [LunatriusCore](LunatriusCore-1.7.10-1.1.2.14-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineTweaker3{3.0.9B} [MineTweaker 3](MineTweaker3-1.7.10-3.0.9C.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ModTweaker{0.6} [ModTweaker](ModTweaker-1.7.X-0.6-0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ObsidianBoat{v1.3.2} [Obsidian Boat](ObsidianBoat-1.7.10-1.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Oceancraft{1.4.1} [Oceancraft](Oceancraft-1.4.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenMods{0.6} [OpenMods](OpenModsLib-1.7.10-0.6-snapshot-249.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenBlocks{1.3} [OpenBlocks](OpenBlocks-1.7.10-1.3-snapshot-481.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    desertcraft{1.7.2b} [Pam's DesertCraft](Pam's DesertCraft 1.7.10a.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    harvestcraft{1.7.10b} [Pam's HarvestCraft](Pam's HarvestCraft 1.7.10c.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AS_Ruins{14.2} [Ruins Spawning System](Ruins-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Schematica{1.7.3.99} [Schematica](Schematica-1.7.10-1.7.3.99-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    simplecobalt{1.7.10-1.4.0} [Simple Cobalt](simplecobalt-1.7.10-1.4.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    simpletungsten{1.3.0} [Simple Tungsten](simpletungsten-1.7.10-1.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    sinhikabark{1.7.2-0.03} [Sinhika's Bark](SinhikaBark-1.7.2-0.03.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    SpiceOfLife{1.2.1} [The Spice of Life](SpiceOfLife-mc1.7.10-1.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    steelyglint{1.1.0} [Steely Glint](SteelyGlint-1.7.10-1.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    sterlingandblack{1.7.10-1.4.2} [Sterling and Black](SterlingAndBlack-1.7.10-1.4.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    StorageDrawers{1.1.4} [Storage Drawers](StorageDrawers-1.7.10-1.1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThaumcraftMobAspects{1.7.2-2A} [Thaumcraft Mob Aspects](ThaumcraftMobAspects-1.7.2-2A.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThaumicTinkerer{2.5-1.7.10-158} [Thaumic Tinkerer](ThaumicTinkerer-2.5-1.7.10-158.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThaumicExploration{0.6.0} [Thaumic Exploration](ThaumicExploration-1.7.10-1.1-17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TiCTooltips{1.1.11b} [TiC Tooltips](TiCTooltips-mc1.7.10-1.1.11b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    UndergroundBiomes{0.6h} [Underground Biomes Constructs](UndergroundBiomesConstructs-1.7.2-0.6h11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AS_UpdateCheck{1.1.6} [AtomicStryker Update Check Mod](UpdateCheckerMod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    WailaHarvestability{1.1.0} [Waila Harvestability](WailaHarvestability-mc1.7.x-1.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    aobd{2.2.4} [Another One Bites The Dust](AOBD-2.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    JustAnotherSpawner{0.14.12} [Just Another Spawner](JustAnotherSpawner-0.14.12.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenModsLib crash transformers: [gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED],[map_gen_fix:FINISHED],[movement_callback:FINISHED],[stencil_patches:FINISHED]
    Mantle Environment: Environment healthy.
    TConstruct Environment: Environment healthy.
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 1 / 8; [EntityPlayerMP['Sinhika'/248, l='RuinsTesting', x=469.54, y=8.40, z=-146.16]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Sinhika** [comment]
Fixed this a while back
